spring.application.name=fitbud-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fitbud
spring.datasource.username=postgres
spring.datasource.password=your_password
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=very-very-ultra-secret-key-very-very-ultra-secret-key
jwt.expiration=3600000
